### ISSUE TITLE
Were do I add the api key and how do I get it

### ISSUE THREAD

**Issue by Kaydeno113** [nextcloud/weather#101]
I installed weather as anyone wood, when I go to add a town or city it says fatal error check logs
I go to the website provided (this GitHub page) it tells me to add the OpenWeatherMap API key.
I do not see how to get it I checked the app store but I do not see an option for OpenWeatherMap API key or OpenWeatherMap

Please help
Thanks

**Comment by Kaydeno113** [comment]
Update I found where to add the API key but how do I get it???

**Comment by nerzhul** [comment]
Hello, you need to go on openweathermap website and create an account
Good luck :)

**Comment by p-bo** [comment]
@Kaydeno113 Where did you found these settings please? In texts in app there is stated:
`Your OpenWeatherMap API key is invalid. Contact your administrator to configure a valid API key in Additional Settings of the Administration`
But in Settings -> Administration section -> Additional Settings, there are settings for other apps, but nothing for Weather :-(
(Nextcloud 24.0.3, latest Weather app)
@nerzhul Could it be somehow related to https://github.com/nextcloud/weather/issues/102 please?

**Comment by p-bo** [comment]
@Kaydeno113 @nerzhul Nevermind - interchanged Weather and Weather status app - sorry for that.
