### ISSUE TITLE
Please add compatibility with Nextcloud V25

### ISSUE THREAD

**Issue by EmJotGeh** [nextcloud/weather#105]
some issues with the new Nextcloud Design.

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by e-alfred** [comment]
Version 1.7.7 now support Nextcloud 24 and 25.
