### ISSUE TITLE
Tries loading resources from wrong location

### ISSUE THREAD

**Issue by NateChambers** [nextcloud/weather#11]
ownCloud version: 8.1.1
PHP version: 5.4
HTTPd server: Apache2
HTTPS: No
owncloud-weather: 1.2.0

Tries to load images in the apps/weather/img folder from http://domain.tld/img/XXX.png instead of however it be loading them. Which results in a 404 not found.

![9-15-2015 1-39-09 am](https://cloud.githubusercontent.com/assets/1159250/9868709/2d570bd4-5b4a-11e5-840f-1816e91268e3.png)

**Comment by e-alfred** [comment]
The same problem appears if index..php is activated.

**Comment by JackFarrand** [comment]
Same issue here, getting 404s and 403s everywhere when loading from the img folder

**Comment by nerzhul** [comment]
sorry it's a long time issue, i should look at it soon

**Comment by e-alfred** [comment]
As this issue is quite old now I am not sure if still applies nowadays. Therefore I would like to close this issue. Please report if it still happens and I will reopen it.
