### ISSUE TITLE
Internal Server Error when set the location

### ISSUE THREAD

**Issue by wxf26054** [nextcloud/weather#111]
### Server configuration

**Operating system: CentOS 8

**Web server: Apache2.4

**Database: MySQL 8.0

**PHP version: 8.0
###
---
When set the weather location, the F12 console shows as the following
![image](https://github.com/nextcloud/weather/assets/22016320/932dc852-1b8d-4dac-935e-acf55a179af9)

Open the metioned URL "http://nc.amazehome.xyz/ocs/v2.php/apps/weather_status/api/v1/location" it shows me 
![image](https://github.com/nextcloud/weather/assets/22016320/36ee29a7-175a-4841-9b24-717f30273146)

**Comment by joshtrichards** [comment]
Your report is for the `weather_status` app which isn't this app here. Additionally, that looks like a configuration problem in your environment - please get troubleshooting assistance via the Nextcloud Help Forum at https://help.nextcloud.com
