### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by webislands** [nextcloud/weather#13]
i have latest version and imposible add this city http://openweathermap.org/city/6354895 
check you validation city plz i am using offical nma and many many time

**Comment by nerzhul** [comment]
In fact the city is sent as is to openweathermap, maybe there is another problem, will look at this tomorrow

**Comment by extrablind** [comment]
Quickly : It seems to be due to 404 error on this specific URL : /index.php/apps/weather/city/add

**Comment by nerzhul** [comment]
404 is returned when the OWM API return 404 in fact

**Comment by gsantner** [comment]
Same here:

![grafik](https://cloud.githubusercontent.com/assets/6735650/23438273/88499ee2-fe11-11e6-9895-c443c247179a.png)
![grafik](https://cloud.githubusercontent.com/assets/6735650/23438283/932725fa-fe11-11e6-8a55-2539b442c40f.png)

**Comment by nerzhul** [comment]
The server side part logs can be useful

**Comment by SpiGAndromeda** [comment]
I have the same problem.

Server logs show the following line:

`[autoindex:error] [pid 11190] [client xx.xxx.xxx.xx:60249] AH01276: Cannot serve directory /var/www/nextcloud/apps/weather/img/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive`

Thats the apache vhost:
        DocumentRoot /var/www/nextcloud

        Alias /nextcloud "/var/www/nextcloud/"

        <IfModule mod_headers.c>

                Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"

        </IfModule>

        SSLEngine On

        CustomLog /var/log/apache2/xxx/access.log common
        ErrorLog /var/log/apache2/xxx/error.log

        RewriteEngine On
        SSLStrictSNIVHostCheck on
        SSLCertificateFile /etc/letsencrypt/live/xxx/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/xxx/privkey.pem

        <Directory /var/www/nextcloud/>

                Options +FollowSymlinks
                AllowOverride All

                <IfModule mod_dav.c>
                        Dav off
                </IfModule>

                SetEnv HOME /var/www/nextcloud
                SetEnv HTTP_HOME /var/www/nextcloud

        </Directory>

        <Directory /mnt/Cloud/Nextcloud>
                Options Indexes FollowSymLinks
                AllowOverride None
                Require all granted
        </Directory>

**Comment by MariusBluem** [comment]
Are you sure you have set an OpenWeatherMap API Key?

**Comment by SpiGAndromeda** [comment]
No I dit not ... I didn't even know that this is required. How to do so?

**Comment by MariusBluem** [comment]
You'll need to register for an API key over here: http://openweathermap.org/price
Then, you can set this key in the apps settings - it can take up to 5 minutes until the cities are found 😬

**Comment by MariusBluem** [comment]
We should make this more clear @nerzhul

**Comment by nerzhul** [comment]
@MariusBluem ofc

**Comment by gsantner** [comment]
If the error says "No city with this name found", nobody can guess that the key is missing. It's a wrong error message in this case.

Also, it seems somewhat a bad idea, that every user has to provide his own key. If I activate this, and a friend logs in he just want to use it, it's not his job to administrate and enter keys. --> Issue no 24

**Comment by Anon01234** [comment]
Hi, Maybe this will help. The app is working but i can add a city. When i look into the logs i see this:

Login failed: 'email@address.here' (Remote IP: '188.206.102.52')

email@address.here = your personal email address given in your profile.

Sorry if this is something not related.

**Comment by nerzhul** [comment]
We don't use any mail address anywhere for remote calls, only OWM API token is used.

**Comment by Anon01234** [comment]
Hi, I figured it out and I understand it. Nice work btw ;)

**Comment by webislands** [comment]
My probleme is ok . i dont have see the place enter api key in setting in left down section

**Comment by tflidd** [comment]
Two points:

- if there is no API key, don't let the user add a city, indicated that the API key is missing
- if possible, differentiate between a city not found and other problems (no valid API key, connection problems, ...)

**Comment by QkiZMR** [comment]
I added API and still get 404 on add city.

**Comment by nerzhul** [comment]
Issue is now fixed in master, an URL encoding error was present and was fixed
