### ISSUE TITLE
Release in Nextclouds App Store

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/weather#19]
As soon as 

- [x] https://github.com/nextcloud/app-certificate-requests/pull/53
- [x] #18 (Rebranding of Repository and this App (especially info.xml)

is done, we should check - whether this app is working with Nextcloud 11 and then **RELEASE** 🙌 

@nerzhul

**Comment by nerzhul** [comment]
App is working with 11.0.1 as i'm using it on my server.

**Comment by MariusBluem** [comment]
I have tested it too 👊🙈

**Comment by nerzhul** [comment]
Done https://apps.nextcloud.com/apps/weather
