### ISSUE TITLE
Sidebar should match with Nextclouds 

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/weather#21]
Nextcloud Weather:

<img width="323" alt="bildschirmfoto 2017-02-27 um 18 15 28" src="https://cloud.githubusercontent.com/assets/19711361/23373409/230a1a4e-fd20-11e6-897c-70cc72e73b5a.png">

Nextcloud Files:

<img width="347" alt="bildschirmfoto 2017-02-27 um 19 08 04" src="https://cloud.githubusercontent.com/assets/19711361/23373415/2aec1492-fd20-11e6-9f40-a78ca1ef45e1.png">

@nerzhul @nextcloud/designers

**Comment by nerzhul** [comment]
If there is a framework option to do it easily i can port it

**Comment by MorrisJobke** [comment]
> If there is a framework option to do it easily i can port it

It's basically using the same CSS classes (and DOM structure) as the files app.

**Comment by cubefoo** [comment]
@nerzhul // fix for this was also included in last patch (line 6 in style.css)
sorry, it's my first contribution on github so I guess I didn't mark this properly after I opened 2 pull requests for the same file

**Comment by nerzhul** [comment]
No problem :)

**Comment by jancborchardt** [comment]
@cubefoo great design contributions there! :) Keep it coming ;)
