### ISSUE TITLE
Load first City when App is started

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/weather#22]
...otherwise it will cause a blank screen for the user, which is not very nice ;)

@nerzhul

**Comment by nerzhul** [comment]
what is "first city" ? maybe we should use browser GPS ?

**Comment by MariusBluem** [comment]
If you have not set your home - the first city in your list should "act" as home and should be loaded :)

**Comment by nerzhul** [comment]
Oh i see, yes could be a nice idea. I'm very busy these days but maybe i can provide a patchset this week

**Comment by tflidd** [comment]
If there are only a few cities, you can also show all cities. Or make it like in most mobile phone apps:
show a list on the front page with each city name, temperature and a sunny/cloudy-symbol, on a click you open a drop-down box with more details of this location.

**Comment by nerzhul** [comment]
I'm working on it in various ways

**Comment by nerzhul** [comment]
Fixed by b2161ce37a9de8ce3a8fdf856ba90dc05f158a2b
