### ISSUE TITLE
Make App Icon less light / Show it on app details page

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/weather#23]
The app icon is a bit to light:
<img width="90" alt="bildschirmfoto 2017-02-27 um 19 10 46" src="https://cloud.githubusercontent.com/assets/19711361/23373548/c5097588-fd20-11e6-809e-856c9adfe292.png">

It should be also shown on the details page:
<img width="254" alt="bildschirmfoto 2017-02-27 um 19 11 20" src="https://cloud.githubusercontent.com/assets/19711361/23373491/8ccab38a-fd20-11e6-9f59-f8167f5d829c.png">

@nerzhul

**Comment by nickvergessen** [comment]
For the apps management page the icon needs to be named `app.svg` or `weather.svg`

**Comment by e-alfred** [comment]
I think this issue is fixed now for some time already. Please reopen if there is still some problem with the icons.
