### ISSUE TITLE
API Key for OpenWeatherMap should be provided by the Administrator

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/weather#24]
...this would make it easier for users to simply **use** this app without handling any API keys 😉 

Maybe the Administrator could also leave the field blank, which would mean - that the user needs to provide a key 🤔 

What do you think? @nerzhul

**Comment by nerzhul** [comment]
@MariusBluem this could be a nice idea, i'm not very familiar with admin app settings

**Comment by nerzhul** [comment]
In progress

**Comment by nerzhul** [comment]
Done in tag 1.5.0
