### ISSUE TITLE
Think about the images and where they are stored

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/weather#28]
See https://github.com/nextcloud/server/issues/3846 ... Weather is a more than huge application if you compare it with other apps like calendar or other apps. This is because of the large image files, this app ships 😁 

Maybe we should think about the way the images are stored - and maybe also host them somewhere else 🤔 

@nerzhul

**Comment by nerzhul** [comment]
Hosting somewhere else permits to track user easily. Also in some configurations, it's not allowed to hotlink. I reduced the png sizes with this commit: 815137fc889637bf42d3785953ab00165fa4356f

This will enhance a little bit user experience
