### ISSUE TITLE
Provide a smaller screenshot for the app store

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/weather#29]
Hi, the current app store upload features a screenshot (https://github.com/nextcloud/weather/blob/master/screenshots/1.png) which is 2Mb big.

It would be cool if someone could reduce the size so that the app list loads faster. The preferred way is to use the **small-thumbnail** attribute for the preview image, see https://github.com/nextcloud/news/blob/master/appinfo/info.xml#L25

**Comment by nerzhul** [comment]
Done 6f130a0d41203b8df81171215a548e34523e25df
