### ISSUE TITLE
background image is not responsive and repeats

### ISSUE THREAD

**Issue by cubefoo** [nextcloud/weather#31]
### Steps to reproduce
1. click on city name so background image appears
2. enlarge your browser window to max. width 
(for image to repeat you screen needs to be larger than background image size)

### Expected behaviour
Background image should
- show the complete image (as much as possible according to screen size)
- scale according to browser window size (responsive behaviour)

### Actual behaviour
Background image
- is only shown partially
- starts repeating if browser window is larger than background image

### Client configuration
**Browser:**
Tested in Safari, Firefox and Chrome

![Image of repeating background image](http://i.imgur.com/HbZj4EM.png)

**Comment by nerzhul** [comment]
Thanks for your contributions
