### ISSUE TITLE
Save button doesn't work in admin settings

### ISSUE THREAD

**Issue by Stibila** [nextcloud/weather#35]
### Steps to reproduce
1. Go to Admin -> Additional settings
2. Provide OpenWeatherMap API Key 
3. Click on Save button

### Expected behaviour
API Key being saved

### Actual behaviour
Nothing

### Server configuration

**Operating system**:
CentOS 7.3.1611

**Web server:**
Nginx 1.12.0

**Database:**
MariaDB 5.5.52

**PHP version:**
7.1.4

**Nextcloud version:** (see Nextcloud admin page)
11.0.3

### Logs
All logs are empty.

**Comment by nerzhul** [comment]
oh sorry it was accidentally released. This feature is not finished yet... you should use personnal setting atm

**Comment by tavinus** [comment]
Heh!  
Took me a few hours for me to get here too...  
  
Does the app store update from master?  
It would be nice to have the admin setting working, but maybe disable the option in the master while it is not yet implemented?

**Comment by nerzhul** [comment]
Yes i just miss some time i'm working on other free projects at the same time, i hope some can help us to contribute or having a second developer on the project can be nice :)

**Comment by kylerschin** [comment]
Yep.... Me too....
![image](https://cloud.githubusercontent.com/assets/7539174/26781188/1735828e-49a2-11e7-9766-8e146541c684.png)

**Comment by xXSTrikeXx** [comment]
Has someone got a solution for saving it globally in admin setts?

**Comment by MariusBluem** [comment]
> Has someone got a solution for saving it globally in admin setts?

This is not implemented yet ;)

**Comment by nerzhul** [comment]
Yes sorry, i should patch it but i'm very busy , you can also propose a pr to drop Old user setting and create handler for admin setting

**Comment by nerzhul** [comment]
Working on it

**Comment by hofmannmartin** [comment]
As this might be related I post it here: There is no field to provide the api key in my personal settings.

### Server configuration

#### Operating system:
Debian 9.0
#### Web server:
Apache 2.4.25
#### Database:
MariaDB 10.1
#### PHP version:
7.0
#### Nextcloud version: (see Nextcloud admin page)
12.0.0

**Comment by nerzhul** [comment]
master is not stable, if you are trying to use it.

**Comment by hofmannmartin** [comment]
I am using the version 1.4.2

**Comment by nerzhul** [comment]
Solved in 1.5.0

**Comment by dps27049** [comment]
I have the same issue. Using 1.5.1. Still says key is invalid.

**Comment by andriusign** [comment]
When is this gonna be fixed? Still not working. C'mon guys, what's the problem?
