### ISSUE TITLE
Weather app does not load / loads entirely white page

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/weather#36]
### Steps to reproduce
1. Install weather app
2. Open app
3. Behold the beauty of an entirely white page

### Expected behaviour
The app starts

### Actual behaviour
The app does not start but an entirely white page is shown

### Server configuration
**Operating system**: Linux holger-kinkelin.de 3.2.0-4-686-pae #1 SMP Debian 3.2.68-1+deb7u6 i686

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 5.5.55

**PHP version:** 5.6.30-0+deb8u1
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, apcu, curl, gd, json, mcrypt, mysql, mysqli, pdo_mysql, pdo_sqlite, readline, sqlite3, mhash, apc, Zend OPcache

**Nextcloud version:** 12.0 RC3 - 12.0.0.26

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - calendar: 1.5.2
 - contacts: 1.5.3
 - dav: 1.3.0
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.2.0
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - updatenotification: 1.2.0
 - weather: 1.4.1
 - workflowengine: 1.2.0

Disabled:
 - comments
 - files_external
 - files_versions
 - files_videoplayer
 - systemtags
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "oct67191dgn6",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "holgercloud.tk"
    ],
    "datadirectory": "\/var\/www\/ownclouddata",
    "overwrite.cli.url": "https:\/\/holgercloud.tk",
    "dbtype": "mysql",
    "version": "12.0.0.26",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "mail_from_address": "nextcloud",
    "mail_domain": "holgercloud.tk",
    "versions_retention_obligation": "5",
    "maintenance": false,
    "log_type": "syslog",
    "logfile": "\/var\/log\/nextcloud.log",
    "loglevel": "5",
    "trashbin_retention_obligation": "7, 28",
    "activity_expire_days": 14,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "theme": "",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by nerzhul** [comment]
hello, a screenshot and console logs from browser is appreciated

**Comment by ho1ger** [comment]
{"reqId":"IIWW44Rvy464VmJAh0Cl","level":3,"time":"2017-05-21T13:17:12+00:00","remoteAddr":"127.0.0.1","user":"xxx","app":"PHP","method":"GET","url":"\/index.php\/apps\/weather\/","message":"Call to undefined method OC\\Server::getDb() at \/var\/www\/html\/xxx\/apps\/weather\/appinfo\/application.php#43","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit\/603.1.30 (KHTML, like Gecko) Version\/10.1 Safari\/603.1.30","version":"12.0.0.26"}


<img width="1440" alt="bildschirmfoto 2017-05-21 um 15 17 14" src="https://cloud.githubusercontent.com/assets/8535968/26284334/b655248e-3e38-11e7-87be-a7405afd0657.png">

**Comment by nerzhul** [comment]
nextcloud 12 compat fixed. Please update to 1.4.2
