### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by D4rkPh0en1x** [nextcloud/weather#37]
Hi

I just installed a fresh copy of Nextcloud 12 an activated the weather app to.
Reading here that the admin settings for the api key doesn't work yet I entered it on the weather page itself but when a city I'm just getting a fatal error.

In the log I can see this:
Undefined index: openweathermap_api_key at /home/cloud/public_html/apps/weather/templates/admin.php#6

**Comment by nerzhul** [comment]
Hello,
this is for the admin setting not the client setting itself it's not problematic for making app to work as admin setting is not used

**Comment by D4rkPh0en1x** [comment]
Yes I know? That is what I wrote as I read it here. I first thought it was due that there the API Key isn't saved but than I found the post here. But even entering the key where it should be and where it is saved it doesn't work so...

**Comment by nerzhul** [comment]
strange, i reinstalled weather on my nextcloud 12 recently and it works. Do you have any log (HTTP log) when adding the key ? what is the answer when trying to add a city

**Comment by D4rkPh0en1x** [comment]
Hi
For me it's no comprehensible. I deactivated the app yesterday and nof for the testing to check in my apache log I reactivated it again and now it simply works??
Miracle? Who knows...

**Comment by anomaly256** [comment]
I have this same problem.  I've tried removing/adding it a few times, isn't working.  Same error when I browse to the admin settings to set the api key:

Undefined index: openweathermap_api_key at /var/www/nextcloud/apps/weather/templates/admin.php#6

I don't think it's creating its db entries correctly

**Comment by anomaly256** [comment]
Oook.  I figured it out.  The presence of the api key field in admin settings was confusing and misleading.  Perhaps this should be removed or disabled until that feature is ready?
