### ISSUE TITLE
City Add Error

### ISSUE THREAD

**Issue by benyanke** [nextcloud/weather#39]
![image](https://user-images.githubusercontent.com/4274911/27562322-b44b9090-5a91-11e7-8ed0-7bb5b54b39fb.png)

Upon adding a city to the weather list, I receive this error. Owncloud.log (I assume you mean /data/nextcloud.log?) shows the following:

`{"reqId":"OOWphagsJRaPg3D2T63M","level":3,"time":"2017-06-26T22:02:46+00:00","remoteAddr":"71.13.249.254","user":"benyanke","app":"PHP","method":"GET","url":"\/settings\/admin\/additional","message":"Undefined index: openweathermap_api_key at \/var\/www\/cloud.work.publicserver.xyz\/public_html\/apps\/weather\/templates\/admin.php#6","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.104 Safari\/537.36","version":"12.0.0.29"}
`

### Server configuration

**Operating system**: Ubuntu 16.04.1

**Web server:** Nginx, using the official config

**Database:** MariaDB

**PHP version:** 7

**Nextcloud version:** 12

**Comment by nerzhul** [comment]
i really should finish this admin template... duplicate closing, thanks for your report
