### ISSUE TITLE
After upgrading to 1.5.0: Can't add API key anymore

### ISSUE THREAD

**Issue by AquaL1te** [nextcloud/weather#41]
### Steps to reproduce
1. Upgrade from the app list menu

### Expected behaviour
A working app with the same working API key, but the settings menu doesn't allow me to set an API key and the app complains that there is non set.

### Actual behaviour
Can't get any weather anymore due to missing API key and the settings menu doesn't pop-up, so can't set the key anymore.

### Server configuration

**Operating system**: Raspbian 8

**Web server:** Apache 2.4

**Database:** Mysql 15.1

**PHP version:** 5.6.30

**Nextcloud version:** (see Nextcloud admin page) 11

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:** Website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>Enabled:
  - activity: 2.4.1
  - audioplayer: 2.0.2
  - calendar: 1.5.3
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.2.0
  - nextcloud_announcements: 1.0
  - notes: 2.3.1
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - rainloop: 5.0.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - twofactor_u2f: 1.3.2
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
</summary>

</details>

### Client configuration
**Browser:** Chrome

**Operating system:** Fedora 25

#### Nextcloud log (data/nextcloud.log)
{"reqId":"OpAkysyAGdKtGyHoRoR8","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgradeStarted: Updating <weather> ...","level":1,"time":"2017-05-25T13:28:11+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}
{"reqId":"OpAkysyAGdKtGyHoRoR8","remoteAddr":"","app":"updater","message":"\\OC\\Updater::appUpgrade: Updated <weather> to 1.4.2","level":1,"time":"2017-05-25T13:28:11+00:00","method":"--","url":"--","user":"--","version":"11.0.3.2"}

{"reqId":"WSbc-goBAAEAAEplZxEAAAAE","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined index: openweathermap_api_key at \/var\/www\/nextcloud\/apps\/weather\/templates\/admin.php#6","level":3,"time":"2017-05-25T13:32:47+00:00","method":"GET","url":"\/settings\/admin\/additional","user":"admin","version":"11.0.3.2"}

</details>

**Comment by AquaL1te** [comment]
Removing the config with occ doesn't help. Reinstalling the app doesn't work.

**Comment by nerzhul** [comment]
hello,
you don't see the api key menu in additional section of admin settings ?

**Comment by AquaL1te** [comment]
That did the trick. Thanks.

**Comment by nerzhul** [comment]
yeah i changed the behaviour to be more friendly for a shared instance :)

**Comment by e-alfred** [comment]
I still had to disable and reenable the app to see the API key setting in the admin page after upgrading to 1.5.0.

**Comment by nerzhul** [comment]
yeah it's a very strange behaviour but it's due to nextcloud admin caching it seems

**Comment by C0rn3j** [comment]
@nerzhul 
>you don't see the api key menu in additional section of admin settings ?

Could this be made more clearer? As someone who isn't used to Nextcloud's app config I had to dig out this issue to figure out it was in the *additional settings* section.

Current error message is as follows.

---

>Your OpenWeatherMap API key is invalid. Contact your administrator to configure a valid API key in 
administration settings

---

I'd perhaps change it to something more explanatory like this 


---

>Your OpenWeatherMap API key is invalid. Contact your administrator to configure a valid API key in administration settings(additional settings section)

---

**Comment by nerzhul** [comment]
@C0rn3j feel free to publish a PR :)
