### ISSUE TITLE
Error message: "Your OpenWeatherMap API key is invalid..."

### ISSUE THREAD

**Issue by dm-m** [nextcloud/weather#43]
### Steps to reproduce
1. Access the app
2. See the error message

### Expected behaviour
Weather details should have been shown without any issues since it was working before for some period of time.

### Actual behaviour
A red error message about invalid API key was shown and there was no place to insert an API key in the Settings (screenshots attached).
![error1](https://user-images.githubusercontent.com/15848442/28064151-36f0a656-663c-11e7-8320-2959f38f42d7.png)
![error2](https://user-images.githubusercontent.com/15848442/28064155-3affdb5e-663c-11e7-86f3-fa9f5a5bdcc4.png)

### Server configuration

**Operating system**: Linux 4.4.38-std-1 #1 SMP Mon Dec 12 10:45:29 UTC 2016 x86_64

**Web server:** nginx/1.13.0 (fpm-fcgi)

**Database:** mysql 10.0.29

**PHP version:** 7.0.15-0ubuntu0.16.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, memcache, mysqli, pdo_mysql, Phar, posix, pspell, readline, recode, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install: updated some time ago**

**Where did you install Nextcloud from: from source** 

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - activitylog: 0.0.1
 - admin_audit: 1.1.0
 - apporder: 0.3.3
 - audioplayer: 2.0.2
 - bookmarks: 0.10.0
 - calendar: 1.5.3
 - comments: 1.1.0
 - dav: 1.1.1
 - direct_menu: 0.10.2
 - drawio: 0.8.8
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_pdfviewer: 1.0.1
 - files_reader: 1.0.4
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - richdocuments: 1.11.33
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - spreed: 1.2.0
 - spreedme: 0.3.9
 - systemtags: 1.1.3
 - tasks: 0.9.5
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - twofactor_totp: 1.1.0
 - updatenotification: 1.1.1
 - weather: 1.5.0
 - workflowengine: 1.1.1

Disabled:
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_external
 - files_retention
 - survey_client
 - templateeditor
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "\/var\/www\/nextcloud\/data",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "singleuser": false,
    "token_auth_enforced": false,
    "auth.bruteforce.protection.enabled": true,
    "knowledgebaseenabled": true,
    "enable_avatars": true,
    "allow_user_to_change_display_name": true
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/59.0.3071.109 Chrome/59.0.3071.109 Safari/537.36

**Operating system:** Linux Mint 18.1 Serena

#### Browser log
<details>
	<summary>Browser log</summary>
	DevTools failed to parse SourceMap: https://***REMOVED***/core/vendor/jquery/dist/jquery.min.map
jquery.min.js?v=3528a03…:2 [Violation] 'DOMContentLoaded' handler took 167ms
[Violation] Forced reflow while executing JavaScript took 138ms
angular.min.js?v=3528a03…:sourcemap:123 TypeError: $scope.loadApiKey is not a function
    at app.js?v=3528a03…:65
    at angular.min.js?v=3528a03…:sourcemap:161
    at e (angular.min.js?v=3528a03…:sourcemap:48)
    at angular.min.js?v=3528a03…:sourcemap:51
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:123
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:95
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:161
e @ angular.min.js?v=3528a03…:sourcemap:48
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:51
angular.min.js?v=3528a03…:sourcemap:123 TypeError: $scope.loadApiKey is not a function
    at app.js?v=3528a03…:65
    at angular.min.js?v=3528a03…:sourcemap:161
    at e (angular.min.js?v=3528a03…:sourcemap:48)
    at angular.min.js?v=3528a03…:sourcemap:51 "Possibly unhandled rejection: {}"
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:123
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:95
g @ angular.min.js?v=3528a03…:sourcemap:134
$digest @ angular.min.js?v=3528a03…:sourcemap:145
$apply @ angular.min.js?v=3528a03…:sourcemap:149
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:162
e @ angular.min.js?v=3528a03…:sourcemap:48
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:51
onloadwff.js:59 [Violation] 'setTimeout' handler took 66ms
VM243:1 GET https://***REMOVED***/apps/weather/weather/get?name=Kharkov 401 ()
(anonymous) @ VM243:1
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:108
p @ angular.min.js?v=3528a03…:sourcemap:103
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:101
(anonymous) @ angular.min.js?v=3528a03…:sourcemap:134
$digest @ angular.min.js?v=3528a03…:sourcemap:145
$apply @ angular.min.js?v=3528a03…:sourcemap:149
l @ angular.min.js?v=3528a03…:sourcemap:102
A.onload @ angular.min.js?v=3528a03…:sourcemap:107
DevTools failed to parse SourceMap: https://***REMOVED***
/apps/weather/js/angular.min.js.map
</details>

**Comment by Synochy** [comment]
Just disable and enable the app in application settings
Then in administration, in more application settings, you can enter your Key Again and the App will work.

**Comment by dm-m** [comment]
Thanks, that did it.
It would be great if you ship some message about the changes in the app and what should be done to reenable it.
