### ISSUE TITLE
Display more forecast data depending on display size

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/weather#45]
Hello,

it would be great to have more forecast data displayed depending on display size. On bigger screens, a lot of empty space at the bottom is shown which could be used for additional data (5 days forecast is possible with a free API key).

**Comment by nerzhul** [comment]
if you have some PHP/JS skills don't hesitate to provide a patch, i'm a little bit busy these days

**Comment by e-alfred** [comment]
I would add a date/day field and increase the number of forecasts to the full 5 days. What do you think about that?

**Comment by nerzhul** [comment]
I think it's possible if OWM API permits it

**Comment by e-alfred** [comment]
Okay, this is fixed by https://github.com/nextcloud/weather/pull/73.
