### ISSUE TITLE
Give me an example of openweathermap API Key ? What file may be configure in nextcloud ?

### ISSUE THREAD

**Issue by PatriceLorant** [nextcloud/weather#54]
Hi,
I don't know where I must be writing the API Key and what is the file, must be modify.
What is the name of API Key in the file ?
What is the file ?
Give me an example and the name of the file.
Thanks
Best regards.

**Comment by nerzhul** [comment]
Hello
it's a setting in the left pane of the app

**Comment by PatriceLorant** [comment]
Hi,

I have an error when i wrote a city


Le 01/03/2018 à 22:35, Loïc Blot a écrit :

**Comment by nerzhul** [comment]
I will add a better notice in readme.md, but see the following screenshot in the admin area, enter your API key here

![capture d ecran de 2018-03-02 10-49-32](https://user-images.githubusercontent.com/119752/36893224-81459756-1e07-11e8-83e9-f5d393759e0f.png)

**Comment by PatriceLorant** [comment]
Thanks nerzhul.
Now, It's very well.
But, if I want an API key for each uesrs of Nextcloud, I can't do that.

**Comment by nerzhul** [comment]
@PatriceLorant it was the previous behaviour, and due to the quota limitation of OWM it's unnecessary on nextcloud instances, as the quota will not be reached, except if you have thousands of users

**Comment by nerzhul** [comment]
issue solved
