### ISSUE TITLE
Nextcloud 14 will drop OCP\DB support

### ISSUE THREAD

**Issue by rullzer** [nextcloud/weather#58]
Hi, OCP\DB is deprecated since version 8.1 and will run into the 3 year deprecation time soon. With the upcoming Nextcloud 14 this will not be available anymore. We highly encourage you to move over from to the \OCP\IDBConnection. Preferably even to the IQueryBuilder. If you need help with the migration please reach out to us.

The removal PR: nextcloud/server#8985

**Comment by MorrisJobke** [comment]
Also ref https://github.com/nextcloud/server/issues/7827

**Comment by nerzhul** [comment]
Solved
