### ISSUE TITLE
Download link of the app is down in the Nextcloud app store

### ISSUE THREAD

**Issue by AquaL1te** [nextcloud/weather#59]
[This link](https://apps.nextcloud.com/apps/weather/releases?platform=13#13) in the [Nextcloud app store](https://apps.nextcloud.com/apps/weather/releases?platform=13#13) is down, already for a few days.

**Comment by nerzhul** [comment]
Hello, yes i'm sorry my dedicated crashed and it's in recovery, but it's not easy (motherboard crash)

**Comment by AquaL1te** [comment]
@nerzhul, no worries! I've noticed the website is up again, could you, when you're done with recovering everything, upload the Weather 1.5.1 version again? The latest version available at the moment is the older 1.5.0 release. Thanks!!

**Comment by nerzhul** [comment]
@AquaL1te yes i will do it asap, but i need to restore non nextcloud related data before, and its not easy :)

**Comment by BloodyIron** [comment]
You know, you could just copy the 1.5.1 release tar.gz file into the same folder as 1.5.0 and be done with it. It's been 20 days, and while I was able to get the equivalent file from the github release section here, it would take you maybe a couple minutes to solve this. Could you please find the time in the near future? :)

That being said, thanks for your hard work! :D

**Comment by nerzhul** [comment]
Yes sorry i'm late, it should be back before sunday if i get some time, but i didn't finished to restore all my services

**Comment by Blackraz0r** [comment]
any news here ? ^^

**Comment by nerzhul** [comment]
oh i updated other apps but forget this app, sorry :) will do it soon

**Comment by nerzhul** [comment]
version 1.5.3 has been published & released on github

**Comment by BloodyIron** [comment]
I don't see 1.5.3 on the app store, just 1.5.1

**Comment by nerzhul** [comment]
exact, wtf

**Comment by nerzhul** [comment]
1.5.4 has been released with NC 14 support
