### ISSUE TITLE
translation of clouds and wind

### ISSUE THREAD

**Issue by CHazz** [nextcloud/weather#60]
hi is possible make full translation ? (clear sky, broken clouds etc.) I would like to translate, I just do not know how thanks :)

**Comment by maxolasersquad** [comment]
It looks like all you need to do is update the relevant file in https://github.com/nextcloud/weather/tree/master/l10n For example, see https://github.com/nextcloud/weather/blob/master/l10n/de.json for the German translation.

**Comment by CHazz** [comment]
of course ... but missing half of words (api outputs) "light snow" etc .. translate is not possible

**Comment by j-ed** [comment]
I think the request is more or less related to the weather data set which is being provided by the OpenWeather API. Based on their [FAQ](https://openweathermap.org/current#multi) translations are currently only provided for the description field but not the cloudiness and wind field. If they couldn't provide a list of key words/phrases it would be difficult to translate them.
I did a short check and found e.g. the following words/phrases being used but there might be much more:
```
+-----------------+-----------------+
| CLOUDINESS      | WIND            |
+-----------------+-----------------+
| Broken clouds   | Gentle Breeze   |
| Few clouds      | Light breeze    |
| haze            | Moderate breeze |
| Sky is clear    | NorthEast       |
| Overcast clouds | North-northwest |
|                 | South           |
|                 | South-East      |
|                 | South-southeast |
+-----------------+-----------------+
```

**Comment by j-ed** [comment]
A user has provided a small hack in the help forum to get the strings translated. I think this is not the right way to implement it at the end but it may give a hint what modification is required to get the strings translated. See https://help.nextcloud.com/t/nc-15-0-7-weather-app/52165/8 for the details.

**Comment by e-alfred** [comment]
I created two pull requests (https://github.com/nextcloud/weather/pull/73 and https://github.com/nextcloud/weather/pull/72) that solve the translation problem completely.

@nerzhul Can you merge this and create a release for Nextcloud 16?

**Comment by nerzhul** [comment]
@e-alfred merged one, will review the other later

**Comment by e-alfred** [comment]
This is now fully implemented so this issue can be closed. @nerzhul I would like to make a new release as soon as more translations from Transiflex come in.

![image](https://user-images.githubusercontent.com/10073629/58078170-61644d00-7bae-11e9-8597-07aaf66560bb.png)

**Comment by nerzhul** [comment]
@e-alfred i will try to perform them asap. Can you provide PR for nextcloud v16 compat in the appinfo.xml please ?

**Comment by e-alfred** [comment]
@nerzhul I updated AngularJS to the latest version and bumped the max-version in the info.xml file in this commit: https://github.com/nextcloud/weather/commit/e60c7bccb26ae959feedc63c0c4ddb10a699242d

Please publish a new release to the app store soon.
