### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by v1r0x** [nextcloud/weather#7]
Really cool app, but I miss translations.
For the openweathermap API you can use `&lang=xx`, for the rest an oc-based translation would be great. I could help with german translation ;)

**Comment by nerzhul** [comment]
You are right, we can use the translations, but i need to find the good way because we use some english phrases to do some cases.

**Comment by aspdye** [comment]
Transifex?

**Comment by vincegre** [comment]
Some updates about translation ? as it's still in english :(

**Comment by tux-nerd** [comment]
I like the weather app very well and i miss the translation (in my case german language) so much. Are there some news or possibilities to help you translating the shown weather data in different languages?

**Comment by Truffelhunter** [comment]
As a workaround I did this:

1.) Change the strings in:
../weather/templates/main.php
for example: Perssure -> Luftdruck, Add a City... -> Einen Ort hinzufügen, Hour -> Uhrzeit ...

2.) Since adding cities doesn't work when attaching for example lang=de to the api key, edit following instead:

../weather/lib/Controller/WeatherController.php

squeeze in &lang=de before &q=" 
        private static $apiWeatherURL = "http://api.openweathermap.org/data/2.5/weather?mode=json&lang=de&q=";
        private static $apiForecastURL = "http://api.openweathermap.org/data/2.5/forecast?mode=json&lang=de&q=";

I did this with version 1.5.0

**Comment by nerzhul** [comment]
i started working on it with nextcloud developers, first on static IHM and when it will work work on dynamic data

**Comment by nerzhul** [comment]
translation is now prepared on transifex, templates was successfuly translated to french, i only need to know how to fix CSS according to content size...

**Comment by nerzhul** [comment]
Fixed, it's time for translators to work :p

**Comment by Truffelhunter** [comment]
I can do german. 
Which file?

**Comment by Truffelhunter** [comment]
Great! Works - thanks very much! :-)

**Comment by tux-nerd** [comment]
... yes, for me too. Thank you very much!


Now, nearly all is done. But what about the wind directions? It's still
in english (just like North-East, North, ....)!

Can you tell me, how to fix that?
