### ISSUE TITLE
New maintainership needed

### ISSUE THREAD

**Issue by nerzhul** [nextcloud/weather#70]
As many see this app is not very maintained these days. I don't have time to polish it and invent new features for it.

@nextcloud/vue if some are interested about maintaining this vue.js application tell me, i can give you the keys :)

I think it can be polished and part of core applications at a point

**Comment by jancborchardt** [comment]
@nerzhul thanks a lot for all your work through the years! :)

@georgehrke maybe weather info is something which should be part of the Calendar directly, as it is in Google Calendar and GNOME? Then the interface would be minimal and integration is great. :)

**Comment by georgehrke** [comment]
You can actually already add weather information to your calendar via webcal. http://www.webcal.fi/en-US/manual_subscription.php#popular 😉 

> @georgehrke maybe weather info is something which should be part of the Calendar directly, as it is in Google Calendar and GNOME? Then the interface would be minimal and integration is great. :)

Generally, this is not something i would like to the in the codebase of the calendar app itself. But once we have https://github.com/nextcloud/calendar/issues/812, other apps should be able to hook into the calendar grid rendering process and add weather information.

**Comment by nerzhul** [comment]
is there any candidate to own the repository in the nextcloud team ? or in big contributors ?

**Comment by jancborchardt** [comment]
@jospoortvliet @shironextcloud could we put out some blog and/or social media posts about looking for a new maintainer? @nerzhul maybe you could write something up as a hand-off and make sure the repo is accessible to a possible new person to take over? :) E.g. having a short "Development setup" section like other apps such as [the Social app](https://github.com/nextcloud/social#development-setup).

**Comment by e-alfred** [comment]
It would be sad to see this app go away. There are no deprecated APIs used (at least as soon as this PR is accepted: https://github.com/nextcloud/weather/pull/71) and it works still pretty well. Can you at least make a new release for Nextcloud 16?

**Comment by nerzhul** [comment]
@e-alfred i can try. I merged #71 thanks. Are you interested to take the ownership ?

**Comment by e-alfred** [comment]
That would be my 4th Nextcloud app I maintain then. :wink:

But surely, I could help you out with this app.

**Comment by e-alfred** [comment]
@nerzhul Anything new about https://github.com/nextcloud/weather and https://github.com/nextcloud/ocsms? Both apps work well on Nextcloud 16 and my offer to help out still stands.

**Comment by nerzhul** [comment]
@e-alfred i invited you in the devel team of this app

**Comment by e-alfred** [comment]
@nerzhul I added some nice features (I think at least that they are :smile:) and I think it is ready now for a new release. Can you publish it to the app store?

**Comment by nerzhul** [comment]
version 1.6.0 has been released. Thanks for your work @e-alfred .

**Comment by nerzhul** [comment]
As a side note @e-alfred when you want to release application, you can run locally ./.ci/release_app.sh 1.6.0
This will do what it's needed to minify etc and push the tag and to master :)
After that you go to github releases page you draft a release on the tag and you push the tar ball generated by the script in /tmp

**Comment by e-alfred** [comment]
@nerzhul Thanks for the information, but how does the release get onto the Nextcloud App Store?

**Comment by nerzhul** [comment]
good question, you login using github, and you should see if you can push a release with the signed package
