### ISSUE TITLE
Too few parameters

### ISSUE THREAD

**Issue by mlichtronix** [nextcloud/weather#74]
[index] Error: ArgumentCountError: Too few arguments to function OCA\Weather\Controller\WeatherController::__construct(), 6 passed in /var/snap/nextcloud/13823/nextcloud/extra-apps/weather/lib/AppInfo/Application.php on line 86 and exactly 7 expected at <<closure>>

 0. /var/snap/nextcloud/13823/nextcloud/extra-apps/weather/lib/AppInfo/Application.php line 86
    OCA\Weather\Controller\WeatherController->__construct("weather", OC\AllConfig {}, OC\AppFramework\Http\Request {}, "martin", OCA\Weather\Db\CityMapper {}, OCA\Weather\Db\SettingsMapper {})
 1. /snap/nextcloud/13823/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php line 118
    OCA\Weather\AppInfo\Application->OCA\Weather\AppInfo\{closure}("*** sensitive parameters replaced ***")
 2. /snap/nextcloud/13823/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php line 117
    Pimple\Container->offsetGet("WeatherController")
 3. /snap/nextcloud/13823/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php line 404
    OC\AppFramework\Utility\SimpleContainer->query("WeatherController")
 4. /snap/nextcloud/13823/htdocs/lib/private/AppFramework/DependencyInjection/DIContainer.php line 382
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("WeatherController")
 5. /snap/nextcloud/13823/htdocs/lib/private/AppFramework/App.php line 97
    OC\AppFramework\DependencyInjection\DIContainer->query("WeatherController")
 6. /snap/nextcloud/13823/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("WeatherController", "get", "*** sensitive parameter replaced ***", {_route: "weather.weather.get"})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "weather.weather.get"})
 8. /snap/nextcloud/13823/htdocs/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "weather.weather.get"})
 9. /snap/nextcloud/13823/htdocs/lib/base.php line 975
    OC\Route\Router->match("/apps/weather/weather/get")
10. /snap/nextcloud/13823/htdocs/index.php line 42
    OC::handleRequest()

GET /index.php/apps/weather/weather/get?name="*** sensitive parameters replaced ***"
from 192.168.1.1 by martin at 2019-06-19T20:03:56+00:00

**Comment by e-alfred** [comment]
This seems like a problem with the app not getting updated correctly or something getting cached on your server. Can you try to clear all caches on the server side (usually a restart of the services should help) to see if it resolves the problem?

**Comment by mlichtronix** [comment]
Yes, restart of services helped.Thanx.
