### ISSUE TITLE
weather api 

### ISSUE THREAD

**Issue by dl6dbh** [nextcloud/weather#81]
hallo 
I have nextcloud 17.0.1 and weather installed. where do I have to enter the api of openweather in the admin menu? I cant find no menu item.

**Comment by e-alfred** [comment]
Go to your Nextcloud admin settings and to "additional settings", there you should find the fiel to enter the API key:

![image](https://user-images.githubusercontent.com/10073629/69484484-026ce280-0e34-11ea-95df-732a277823b3.png)

**Comment by dl6dbh** [comment]
hallo 
my problem is i cant find the point additional settings in the admin site

**Comment by dl6dbh** [comment]
i find ... its working
