### ISSUE TITLE
NC 18 compatibility

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/weather#87]
Please release for NC 18

**Comment by e-alfred** [comment]
@nerzhul I already made a release over the weekend, please publish the Weather and OCSMS apps to the app store.

**Comment by e-alfred** [comment]
Nextcloud 18.0.1 is out now, @nerzhul can you pusblish the new releases to the App Store for the Weather app and OCSMS?

**Comment by BloodyIron** [comment]
Okay so can we get this release to the app store? Moving to NC18 right now.

**Comment by nerzhul** [comment]
done

**Comment by nerzhul** [comment]
@e-alfred we may find a way to exchange the signing key as you are now the main maintainer on this app

**Comment by BloodyIron** [comment]
Woot! Thanks! :D

**Comment by e-alfred** [comment]
@nerzhul Please drop me a line at magictimes@protonmail.com.

**Comment by nerzhul** [comment]
done
