### ISSUE TITLE
NC 20 Compatibility

### ISSUE THREAD

**Issue by schniepp** [nextcloud/weather#94]
This app is currently not compatible with NC 20. 

Please update, as I LOVE this app!
Thanks for all your work!

**Comment by almereyda** [comment]
It is working for me on a Nextcloud 20 arm64. What is the error that you are experiencing, might it be #86?

Eventually this has been fixed meanwhile, and the issue can be closed.

**Comment by e-alfred** [comment]
Fixed by https://github.com/nextcloud/weather/releases/tag/1.7.4.
